# Generated by Django 5.2.14 on 2026-06-22 21:30

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post", "created_at"], name="blog_comment_post_created_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("is_published", True)),
                fields=["-created_at"],
                name="blog_post_pub_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.db.models.functions.comparison.Cast(
                            "title", output_field=models.TextField()
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("is_published", True)),
                name="blog_post_title_pub_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.db.models.functions.comparison.Cast(
                            "body", output_field=models.TextField()
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("is_published", True)),
                name="blog_post_body_pub_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="blog_user_email_idx"),
        ),
    ]
